---
- hosts: 192.168.100.162
  tasks:
    - name: Generate variable
      set_fact:
        my_variable: "Hello, World!"

    - name: Set variable as stats
      set_stats:
        data:
          my_variable: "{{ my_variable }}"
